sudo: required

services:
  - docker

before_install:
  - docker build -t mdrahman-upm/docker-startup -f Dockerfile.dev .

script:
  - docker run mdrahman-upm/docker-startup npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker_startup"
  env: "DockerStartup-env"
  bucket_name: "elasticbeanstalk-us-west-2-396017732323"
  bucket_path: "docker_startup"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY